- cmd/okbchaind/main.go
- dev/start.sh
- libs/cosmos-sdk/server/util.go
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))
______
For Admin Use:
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))
> startup by out of box 

- .github/workflows/ci-okbchain-ut.yml
- LICENSE
- Makefile
- README.md
- benchmarks/app_test.go
- dev/start.sh
- libs/cosmos-sdk/baseapp/baseapp_paralled_test.go
- libs/cosmos-sdk/baseapp/evm2cm_test.go
- libs/cosmos-sdk/types/dec_coin_test.go
- libs/cosmos-sdk/types/staking.go
- libs/cosmos-sdk/x/gov/types/msgs_test.go
- libs/system/common.go
- x/common/syscoin_test.go
- x/common/syscoins_test.go
- x/evm/client/utils/utils_test.go
- x/genutil/client/legacy/v0_18/migrate_test.go
- x/staking/client/cli/tx_proposal.go
- x/staking/genesis_test.go
- x/staking/msg_convert_test.go
- x/token/legacy/v0_10/types.go
- x/token/legacy/v0_11/types.go
- x/token/types/token.go
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))
______
For Admin Use:
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))
> rebranding

- dev/testnet/okc.profile
- dev/testnet/testnet.sh
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))
______
For Admin Use:
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))
> update local testnet script

- app/node_mode.go
- app/repair_state.go
- libs/cosmos-sdk/server/pruning.go
- libs/cosmos-sdk/server/start.go
- libs/cosmos-sdk/server/start_okchain.go
- libs/cosmos-sdk/store/mpt/params.go
- libs/cosmos-sdk/store/mpt/store.go
- libs/cosmos-sdk/store/rootmulti/rootmulti_store.go
- libs/iavl/mutable_tree_oec.go
- libs/system/config.go
> mpt async commit config

- libs/cosmos-sdk/baseapp/gasuseddb.go
> fix hgu in ut

- libs/cosmos-sdk/store/mpt/types/wrap_rocksdb.go
> fix compile issue

- libs/cosmos-sdk/store/mpt/store_iterator.go
- libs/cosmos-sdk/store/mpt/store_iterator_test.go
- libs/cosmos-sdk/store/mpt/store_iterator_wrap.go
- libs/cosmos-sdk/x/crisis/abci.go
- libs/cosmos-sdk/x/crisis/internal/keeper/keeper.go
- libs/cosmos-sdk/x/crisis/internal/keeper/keeper_test.go
> wrap mpt iterator

- cmd/okbchaind/main.go
> use invariants check period

- libs/cosmos-sdk/baseapp/gasuseddb.go
- libs/tendermint/mempool/clist_mempool.go
> fix bug of pgu

- app/app.go
- cmd/okbchaind/iaviewer.go
- libs/cosmos-sdk/server/start.go
- libs/cosmos-sdk/server/start_okchain.go
- libs/iavl/mutable_tree_oec.go
> remove unused enable-fast-storage flag

- libs/iavl/mutable_tree_oec.go
> Fix the issue where the program would hang on exit when the pruning="nothing".

- app/repair_state.go
- libs/cosmos-sdk/store/rootmulti/rootmulti_store.go
> Optimize the "repaire-state" command to fix the data generated by async commit.

- app/rpc/namespaces/eth/simulation/impl.go
- libs/cosmos-sdk/store/mpt/store.go
- x/evm/keeper/statedb.go
- x/evm/keeper/statedb_mpt_test.go
- x/evm/types/state_object_mpt.go
- x/evm/types/statedb.go
- x/evm/types/statedb_mpt.go
> fix watchdb for mpt

- Makefile
- app/types/chain_id.go
- libs/cosmos-sdk/server/start_okchain.go
- libs/system/common.go
- libs/tendermint/lite/client/provider.go
- libs/tendermint/types/milestone.go
> Adapt chain-id 

- libs/cosmos-sdk/store/mpt/types/wrap_rocksdb_batch.go
- libs/cosmos-sdk/store/mpt/types/wrap_rocksdb_iterator.go
- libs/tm-db/rocksdb_batch.go
- libs/tm-db/rocksdb_iterator.go
> close db batch and iterator

- .circleci/config.yml
- .github/workflows/ci-okbchain-ut.yml
> update ci go version

- libs/cosmos-sdk/store/mpt/instance.go
- libs/cosmos-sdk/store/mpt/store.go
> Modify ac to adapt to the snapshot

- x/distribution/keeper/invariants.go
> modify distr invariants

- cmd/okbchaind/rest.go
- libs/cosmos-sdk/server/start_okchain.go
> update rest api prefix

- x/staking/handler.go
- x/staking/types/params.go
> default  poa params

- x/evm/keeper/abci.go
- x/evm/types/indexer.go
> fix bloom filter with canonical block unknown error

- app/rpc/namespaces/eth/api.go
- x/evm/keeper/abci.go
- x/evm/watcher/watcher.go
> Fix rpc bugs

- x/evm/keeper/keeper.go
> sanity check get eth block

- libs/cosmos-sdk/store/mpt/store.go
> disable prefetcher

- libs/cosmos-sdk/store/mpt/store.go
> close snapshot after async db close

- app/utils/appstatus/fast_storage.go
- cmd/okbchaind/fss/create.go
- cmd/okbchaind/fss/fss.go
- cmd/okbchaind/mpt/snapshot.go
add  mpt generate snapshot to fss create and rename genSnap to gen-snapshot
______
For Admin Use:
> add  mpt generate snapshot to fss create and rename genSnap to gen-snapshot

- app/rpc/namespaces/eth/api.go
- x/evm/keeper/querier.go
- x/evm/keeper/statedb.go
- x/evm/types/state_object_mpt.go
- x/evm/types/statedb.go
> fix data mismatch while calling eth_call

- .circleci/config.yml
> Fix: circleci working_directory has changed from /go to /home/circleci/go

- libs/cosmos-sdk/store/mpt/store.go
> add update snapshot when commit

- libs/cosmos-sdk/store/internal/maps/maps.go
- libs/cosmos-sdk/store/mpt/asyncdb.go
- libs/cosmos-sdk/store/mpt/asyncdb_iter.go
- libs/cosmos-sdk/store/mpt/asyncdb_iter_test.go
> optimize ac iterator for snapshot

- libs/cosmos-sdk/store/mpt/snapshot.go
- libs/cosmos-sdk/store/mpt/snapshot_test.go
> fix bug when account is created and deleted  in one ac gap

- x/wasm/keeper/keeper.go
- x/wasm/watcher/store.go
> set watch store to prefix praent

- libs/cosmos-sdk/store/mpt/immutable_store.go
- libs/cosmos-sdk/store/mpt/store.go
- libs/cosmos-sdk/store/mpt/store_iterator.go
- libs/cosmos-sdk/store/mpt/store_iterator_test.go
- libs/cosmos-sdk/store/mpt/store_iterator_wrap.go
> wasm on mpt reiterate

- x/wasm/client/rest/query.go
> query code by contract address

- libs/cosmos-sdk/store/mpt/store.go
- libs/cosmos-sdk/store/mpt/store_iterator_test.go
- libs/cosmos-sdk/store/mpt/store_iterator_wrap.go
- x/wasm/module_test.go
> fix the storage iterator's panic

- libs/cosmos-sdk/store/mpt/store.go
- x/wasm/keeper/keeper_mpt.go
- x/wasm/watcher/store.go
> adapter watchdb with prefix

- x/wasm/ibc.go
- x/wasm/keeper/gas_register.go
- x/wasm/keeper/keeper.go
- x/wasm/keeper/proposal_integration_test.go
- x/wasm/keeper/query_plugins.go
- x/wasm/keeper/test_common.go
> wasm rebrand okbchain

- Makefile
- app/app.go
- app/repair_state.go
- dev/proposals/wasm.proposal
- dev/start.sh
- dev/testnet/run4v1r.sh
- libs/cosmos-sdk/store/rootmulti/rootmulti_store.go
- libs/tendermint/types/milestone.go
> upgrade by proposal

- x/params/keeper_upgrade.go
- x/params/keeper_upgrade_test.go
- x/params/types/upgrade_cache.go
- x/params/types/upgrade_cache_test.go
- x/params/upgrade_executor.go
- x/params/upgrade_executor_test.go
> remove map and panic for upgrade proposal

- Makefile
> bump version to v0.1.2

- x/slashing/handler.go
- x/slashing/internal/types/expected_keepers.go
- x/staking/keeper/val_state_change.go
> fix unjail on PoA

- libs/cosmos-sdk/baseapp/baseapp_mode_deliverInAsync.go
> fix vmbridge smb

- cmd/okbchaind/data.go
- libs/cosmos-sdk/store/rootmulti/rootmulti_store.go
> fix maxPruneHeightsLength

- app/config/config.go
- app/rpc/tests/rpc_test.go
- cmd/client/flags.go
- libs/tendermint/config/dynamic_config_okchain.go
- libs/tendermint/lite/proxy/query_test.go
- libs/tendermint/rpc/client/event_test.go
- libs/tendermint/rpc/core/events.go
- libs/tendermint/rpc/core/mempool.go
- libs/tendermint/rpc/grpc/grpc_test.go
> dynamic config max_subscription_clients

- app/node_mode.go
- libs/cosmos-sdk/client/flags/flags.go
- libs/cosmos-sdk/client/lcd/root.go
- libs/cosmos-sdk/server/start_okchain.go
> fix rpc server config issue

- Makefile
> Bump version to v0.1.4

- go.mod
- go.sum
- libs/cosmos-sdk/store/mpt/rawdb_delta.go
- libs/cosmos-sdk/store/mpt/store.go
- x/evm/types/statedb_mpt.go
> dds add rawdb support

- app/rpc/backend/backend.go
- app/rpc/types/utils.go
> limit eth_getBlockByNumber

- libs/cosmos-sdk/baseapp/baseapp_parallel.go
- libs/cosmos-sdk/baseapp/baseapp_runtx.go
> set txhash and type for parallel

- app/app.go
- app/app_parallel.go
- libs/cosmos-sdk/baseapp/baseapp_parallel.go
- libs/cosmos-sdk/types/handler.go
- libs/ibc-go/testing/simapp/app.go
> fix smb caused by e2c txcount

- Makefile
> Bump version to v0.1.5

- libs/cosmos-sdk/baseapp/baseapp_parallel.go
- libs/cosmos-sdk/baseapp/baseapp_runtx.go
> set txhash and type for failed tx

- libs/rocksdb/install.sh
> when compile rocksdb disable tcmalloc by default

- Makefile
> Bump version to v0.1.6

- README.md
> add resources for readme.md

- app/innertx_test.go
- libs/cosmos-sdk/baseapp/baseapp.go
- libs/cosmos-sdk/types/context.go
- libs/cosmos-sdk/x/auth/keeper/account.go
- libs/tendermint/state/execution_dds.go
- libs/tendermint/types/deltas.go
- x/evm/handler.go
- x/evm/handler_test.go
- x/evm/keeper/params_test.go
- x/evm/types/state_transition.go
- x/evm/types/statedb_protect_test.go
- x/evm/types/statedb_test.go
- x/evm/watcher/watcher_test.go
- x/feesplit/keeper/fee_splits.go
- x/params/types/upgrade_cache_test.go
- x/wasm/handler.go
> fix dds wasm

- libs/cosmos-sdk/baseapp/baseapp_parallel.go
> fee : fix para for wasm

- app/app_parallel.go
optimize code
______
For Admin Use:
> optimize the judgment of whether e2c supports parallel execution

- cmd/okbchaind/repair_data.go
> Disable fss when repair set discard-fast-storage

- app/app.go
- libs/cosmos-sdk/types/tx_msg.go
- libs/cosmos-sdk/x/auth/ante/sigverify.go
- libs/cosmos-sdk/x/auth/types/stdtx.go
- libs/tendermint/abci/types/tx.go
- libs/tendermint/mempool/clist_mempool.go
- libs/tendermint/rpc/core/mempool.go
- libs/tendermint/rpc/core/routes.go
- x/evm/types/msg_evm.go
> fix cmtx nonce

- x/evm/types/state_transition.go
> fix the bug of incorrectly assigning err when trace tx

- app/rpc/namespaces/eth/api.go
- x/evm/watcher/evmtx.go
- x/evm/watcher/infura.go
- x/evm/watcher/tx.go
- x/evm/watcher/types.go
- x/evm/watcher/watcher.go
- x/infura/cache.go
- x/infura/keeper.go
- x/infura/types/types.go
> write transaction receipt to watchdb in rpc api

- go.mod
- go.sum
- x/wasm/keeper/keeper.go
- x/wasm/keeper/wasmtesting/mock_engine.go
- x/wasm/types/store_adapter.go
- x/wasm/types/types.go
- x/wasm/types/wasmer_engine.go
> add gas table

- go.mod
- go.sum
- libs/cosmos-sdk/types/context.go
- x/wasm/keeper/api.go
- x/wasm/keeper/contract_keeper.go
- x/wasm/keeper/keeper.go
- x/wasm/types/errors.go
- x/wasm/types/store_adapter.go
- x/wasm/types/validation.go
> wasm create contract

- x/wasm/keeper/keeper.go
> fix merge error

- x/wasm/keeper/cross_contract_call.go
> support instantiate delcall

- app/app.go
- go.mod
- go.sum
- libs/tendermint/types/milestone.go
- x/wasm/module.go
> add venus7 for wasm upgrade

- app/app.go
- go.mod
- go.sum
- libs/cosmos-sdk/types/context.go
- libs/tendermint/types/milestone.go
- x/wasm/keeper/api.go
- x/wasm/keeper/contract_keeper.go
- x/wasm/keeper/cross_contract_call.go
- x/wasm/keeper/cross_contract_call_test.go
- x/wasm/keeper/keeper.go
- x/wasm/keeper/wasmtesting/mock_engine.go
- x/wasm/module.go
- x/wasm/types/errors.go
- x/wasm/types/store_adapter.go
- x/wasm/types/types.go
- x/wasm/types/validation.go
- x/wasm/types/wasmer_engine.go
> wasm40 upgrade
